language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
services:
  - docker

before_script:
  - docker pull debian:jessie

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get remove curl
  - sudo apt-get build-dep curl
  - mkdir ~/curl
  - cd ~/curl
  - wget http://curl.haxx.se/download/curl-7.64.1.tar.bz2
  - tar -xvjf curl-7.64.1.tar.bz2
  - cd curl-7.64.1 && ./configure && make && sudo make install && sudo ldconfig
  - sudo apt-get install docker-ce
  - cd /home/travis/build/donflopez/dockers

  script:
  - cargo build --verbose --all
  - sudo ldconfig && cargo test --verbose --all